### PR TITLE
Samples and links metadata

### LINKED ISSUE #150: create and output links metadata
ToDo list moved to PR https://github.com/oceanprotocol/pleuston/pull/151

Closes https://github.com/oceanprotocol/ocean/issues/123

### PR DESCRIPTION
**Pull request by kremalicious**
**WIP**

* adds the ability to create one or multiple links for an asset, and output them
* reorganize components used on `/new` screen
* new simplified `FormInput` component usage
* closes #150 
* part of https://github.com/oceanprotocol/ocean/issues/123

### ToDo

- [x] `links` is array of link objects
- [x] design and create UI prototype for adding multiple links
- [x] structure link object with `name`, `type`, `url` (following OEP-08 & proposed changes in https://github.com/oceanprotocol/OEPs/pull/82 & https://github.com/oceanprotocol/OEPs/pull/86)

#### adding flow

- [x] remove added link
- [x] return when required fields are empty
- [x] form error feedback
- [x] capture all link form values, send along on full form submit
- [ ] save captured data to aquarius

#### display on AssetFull view

- [x] output all links on asset full view

### Showcase

untitled

---

Default empty state:

screen shot 2018-10-25 at 14 01 46

---

List added links, progressive disclosure of form:

screen shot 2018-10-26 at 14 16 39

---

screen shot 2018-10-26 at 14 16 47

## Types of changes

- [x] New feature (non-breaking change which adds functionality)
 
## Checklist:

- [x] Follows the code style of this project.
- [ ] Tests Cover Changes
- [ ] Documentation

#### Funny gif

giphy

### CODE REVIEW

**Comment by JohnBDB** [comment]
@kremalicious update on this one?

**Comment by kremalicious** [comment]
UI and front-end implementation is done, but we can't save to Aquarius for whatever reason and it's not clear where exactly the problem is. Registering assets in general doesn't work right now, and this PR is blocked until that is resolved

**Comment by kremalicious** [comment]
Described issue in #162

**Comment by kremalicious** [comment]
we merge this although final testing isn't done cause the fix for registering is only working with the other huge branch in #133. Onwards!

giphy

**Pull request merged**
