### PR TITLE
document branching model

### PR DESCRIPTION
**Pull request by kremalicious**

### CODE REVIEW

**Comment by H34D** [comment]
i like to have `develop` as default. How about @aaitor @diminator ?

**Comment by diminator** [comment]
I think it makes sense - we can have tags for the master releases

**Comment by H34D** [comment]
> I think it makes sense - we can have tags for the master releases

we already have tags for `master` releases.

**Comment by diminator** [comment]
> we already have tags for master releases

I wouldn't expect less from professionals like you ;)

**Comment by kremalicious** [comment]
So I'll merge this here and set default branch to `develop` or are there any objections for this repo? This repo's `develop` branch is quite stable cause we always try to keep all tests green for it.

As far as the automatic and manual workflows in this repo are concerned, this would make a lot of sense, and for users it's also an advantage getting the latest fixes and readme. Still discussable if it makes sense in all repos as suggested in https://github.com/oceanprotocol/dev-ocean/pull/43

**Pull request merged**
